// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "20667662-f40f-49e3-8bdd-96a367fdaaec";
const char DEVICE_LOGIN_NAME[]  = "90e0cfc0-9b4e-49a0-9446-6461ccd764a8";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onInvEndChange();
void onChargeStartChange();
void onChargeEndChange();
void onWattsChange();
void onInvStartChange();

float invEnd;
float chargeStart;
float chargeEnd;
int watts;
float invStart;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(invEnd, READWRITE, ON_CHANGE, onInvEndChange);
  ArduinoCloud.addProperty(chargeStart, READWRITE, ON_CHANGE, onChargeStartChange);
  ArduinoCloud.addProperty(chargeEnd, READWRITE, ON_CHANGE, onChargeEndChange);
  ArduinoCloud.addProperty(watts, READWRITE, ON_CHANGE, onWattsChange);
  ArduinoCloud.addProperty(invStart, READWRITE, ON_CHANGE, onInvStartChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
